version: "3.8"

services:
    web:
        image: "nginx"
        container_name: "mynginx2"
        ports:
            - "8081:80"
        networks:
            - default
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./web:/var/www/html
    php:
        #https://github.com/harrison9824003/docker/tree/master/php/fpm/swoole
        image: "harrison9824003/php-swoole:v1.0"
        # image: "php-fpm:swoole"
        container_name: "php-fpm2"
        networks:
            - default
        ports:
            - "9001:9000"
        volumes:
            - ./web:/var/www/html