version: "3.8"

services:
    web:
        image: "nginx"
        container_name: "mynginx"
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./web:/var/www/html
    php:
        image: "php:8.1.12-fpm-alpine"
        container_name: "myphp"
        ports:
            - "9000:9000"
        volumes:
            - ./web:/var/www/html