version: "3.8"

services:
    web:
        image: "nginx"
        container_name: "mynginx"
        ports:
            - "8081:80"
        networks:
            - default
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./web:/var/www/html
    php:
        #https://github.com/harrison9824003/docker/tree/master/php/fpm/swoole
        image: "php-fpm:swoole"
        container_name: "php-fpm"
        networks:
            - default
        ports:
            - "9000:9000"
        volumes:
            - ./web:/var/www/html
    mysql:
        image: "mysql:5.7"
        container_name: "mysql5.7"
        ports:
            - "3306:3306"
        networks:
            - default
        volumes:
            - ./mysql/log:/var/log/mysql
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
    redis:
        image: "redis"
        container_name: "redis"
        ports:
            - "6379:6379"
        privileged: true
        volumes:
            - ./redis/conf/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data