version: "3.8"

services:
    web:
        image: "nginx"
        container_name: "proxy"
        ports:
            - "8080:80"
        networks:
            - default
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
