version: "3.8"

services:
    web:
        image: "nginx"
        container_name: "mynginx"
        ports:
            - "8080:80"
        networks:
            - default
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./web:/var/www/html
    php:
        #image: "php:8.1.12-fpm"
        image: "php-fpm:swoole"
        container_name: "php-fpm"
        networks:
            - default
        ports:
            - "9000:9000"
        volumes:
            - ./web:/var/www/html