version: "3.8"

services:
    mysql:
        image: "mysql:5.7"
        container_name: "mysql5.7"
        ports:
            - "3306:3306"
        networks:
            - default
        volumes:
            - ./log:/var/log/mysql
            - ./data:/var/lib/mysql
            - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: "123456"